export default {
  index: 'Home',
  "overview": "Overview",
  "sample_metadata": "Metadata and QC",
  "metadata_sqlite": "SQLite Metadata",
  "assemblies": "Assemblies",
  "species_id": "Species Calls",
  "annotation": "Annotation",
  "amr": "Antimicrobial Resistance",
  "defense": "Defense systems",
  "bgcs": "Biosynthetic Gene Clusters",
  "hypothetical_protein_structures": "Hypothetical Protein Structures",
  "typing": "Species specific typing",
  "archaea": "Archaea",
  "lexicmap": "Sequence alignment with LexicMap",
  "contributing": "Contributing to AllTheBacteria",
  "osf_downloads": "Batch downloading from OSF",
  "faq": "FAQ",
  "release_history": "Release History",
  "ebi2osf": "Migration From EBI To OSF",
}
